/**
 * Where the landing's links go, in one place. "Probar la demo" and "Entrar a la demo" are the one-click entry when the demo console
 * is on (DemoEntryCta, demo-entry.tsx: one click signs in as the default test customer and lands in the chat). Their address is
 * `demoEntry`, the sign-in, which lists the demo accounts when the API runs with DEMO_MODE: where they go with the console off, or
 * before the page has its script.
 */
export const demoEntry = { to: '/login' } as const
export const signInEntry = { to: '/login' } as const
export const consoleEntry = { to: '/operador/login' } as const

/**
 * The public repository of the submission, generated by ops/export_public.py. The landing never links to the private one;
 * with this set, the evidence grid and the limits link to their documents in it. Set it back to null to draw them without links.
 */
export const publicRepository: string | null = 'https://github.com/try-cecilia/factored-hackathon-2026-cecilia'

/** The ids of the sections the header and the footer link to. */
export const sections = {
  data: 'datos',
  architecture: 'arquitectura',
  results: 'resultados',
  console: 'consola',
  security: 'seguridad',
  operation: 'operacion',
  limits: 'limites',
  evidence: 'evidencia',
} as const
