/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DemobancoRouteImport } from './routes/_demobanco'
import { Route as OperatorRouteImport } from './routes/_operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as OperadorClaveRouteImport } from './routes/operador.clave'
import { Route as OperadorIngresoRouteImport } from './routes/operador.ingreso'
import { Route as OperadorLoginRouteImport } from './routes/operador.login'
import { Route as OperadorSalirRouteImport } from './routes/operador.salir'
import { Route as OperadorSesionRouteImport } from './routes/operador.sesion'
import { Route as DemobancoDemoBancoRouteImport } from './routes/_demobanco/demo.banco'
import { Route as OperatorOperadorIndexRouteImport } from './routes/_operator/operador.index'
import { Route as OperatorOperadorColaRouteImport } from './routes/_operator/operador.cola'
import { Route as OperatorOperadorMonitoreoRouteImport } from './routes/_operator/operador.monitoreo'
import { Route as OperatorOperadorTrazasRouteImport } from './routes/_operator/operador.trazas'
import { Route as ApiAgentHealthRouteImport } from './routes/api.agent.health'
import { Route as DemobancoDemoBancoIndexRouteImport } from './routes/_demobanco/demo.banco.index'
import { Route as DemobancoDemoBancoRastreosRouteImport } from './routes/_demobanco/demo.banco_.rastreos'
import { Route as OperatorOperadorColaIndexRouteImport } from './routes/_operator/operador.cola.index'
import { Route as OperatorOperadorColaTicketIdRouteImport } from './routes/_operator/operador.cola.$ticketId'
import { Route as OperatorOperadorTrazasIndexRouteImport } from './routes/_operator/operador.trazas.index'
import { Route as OperatorOperadorTrazasTraceIdRouteImport } from './routes/_operator/operador.trazas.$traceId'
import { Route as DemobancoDemoBancoCasoTicketIdRouteImport } from './routes/_demobanco/demo.banco.caso.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DemobancoRoute = DemobancoRouteImport.update({
  id: '/_demobanco',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorClaveRoute = OperadorClaveRouteImport.update({
  id: '/operador/clave',
  path: '/operador/clave',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIngresoRoute = OperadorIngresoRouteImport.update({
  id: '/operador/ingreso',
  path: '/operador/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorLoginRoute = OperadorLoginRouteImport.update({
  id: '/operador/login',
  path: '/operador/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorSalirRoute = OperadorSalirRouteImport.update({
  id: '/operador/salir',
  path: '/operador/salir',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorSesionRoute = OperadorSesionRouteImport.update({
  id: '/operador/sesion',
  path: '/operador/sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemobancoDemoBancoRoute = DemobancoDemoBancoRouteImport.update({
  id: '/demo/banco',
  path: '/demo/banco',
  getParentRoute: () => DemobancoRoute,
} as any)
const OperatorOperadorIndexRoute = OperatorOperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOperadorColaRoute = OperatorOperadorColaRouteImport.update({
  id: '/operador/cola',
  path: '/operador/cola',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOperadorMonitoreoRoute =
  OperatorOperadorMonitoreoRouteImport.update({
    id: '/operador/monitoreo',
    path: '/operador/monitoreo',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorOperadorTrazasRoute = OperatorOperadorTrazasRouteImport.update({
  id: '/operador/trazas',
  path: '/operador/trazas',
  getParentRoute: () => OperatorRoute,
} as any)
const ApiAgentHealthRoute = ApiAgentHealthRouteImport.update({
  id: '/api/agent/health',
  path: '/api/agent/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemobancoDemoBancoIndexRoute = DemobancoDemoBancoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemobancoDemoBancoRoute,
} as any)
const DemobancoDemoBancoRastreosRoute =
  DemobancoDemoBancoRastreosRouteImport.update({
    id: '/demo/banco_/rastreos',
    path: '/demo/banco/rastreos',
    getParentRoute: () => DemobancoRoute,
  } as any)
const OperatorOperadorColaIndexRoute =
  OperatorOperadorColaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperatorOperadorColaRoute,
  } as any)
const OperatorOperadorColaTicketIdRoute =
  OperatorOperadorColaTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => OperatorOperadorColaRoute,
  } as any)
const OperatorOperadorTrazasIndexRoute =
  OperatorOperadorTrazasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperatorOperadorTrazasRoute,
  } as any)
const OperatorOperadorTrazasTraceIdRoute =
  OperatorOperadorTrazasTraceIdRouteImport.update({
    id: '/$traceId',
    path: '/$traceId',
    getParentRoute: () => OperatorOperadorTrazasRoute,
  } as any)
const DemobancoDemoBancoCasoTicketIdRoute =
  DemobancoDemoBancoCasoTicketIdRouteImport.update({
    id: '/caso/$ticketId',
    path: '/caso/$ticketId',
    getParentRoute: () => DemobancoDemoBancoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthedChatRoute
  '/dev/ui': typeof DevUiRoute
  '/operador/clave': typeof OperadorClaveRoute
  '/operador/ingreso': typeof OperadorIngresoRoute
  '/operador/login': typeof OperadorLoginRoute
  '/operador/salir': typeof OperadorSalirRoute
  '/operador/sesion': typeof OperadorSesionRoute
  '/demo/banco': typeof DemobancoDemoBancoRouteWithChildren
  '/operador/cola': typeof OperatorOperadorColaRouteWithChildren
  '/operador/monitoreo': typeof OperatorOperadorMonitoreoRoute
  '/operador/trazas': typeof OperatorOperadorTrazasRouteWithChildren
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/operador/': typeof OperatorOperadorIndexRoute
  '/demo/banco/rastreos': typeof DemobancoDemoBancoRastreosRoute
  '/operador/cola/$ticketId': typeof OperatorOperadorColaTicketIdRoute
  '/operador/trazas/$traceId': typeof OperatorOperadorTrazasTraceIdRoute
  '/demo/banco/': typeof DemobancoDemoBancoIndexRoute
  '/operador/cola/': typeof OperatorOperadorColaIndexRoute
  '/operador/trazas/': typeof OperatorOperadorTrazasIndexRoute
  '/demo/banco/caso/$ticketId': typeof DemobancoDemoBancoCasoTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthedChatRoute
  '/dev/ui': typeof DevUiRoute
  '/operador/clave': typeof OperadorClaveRoute
  '/operador/ingreso': typeof OperadorIngresoRoute
  '/operador/login': typeof OperadorLoginRoute
  '/operador/salir': typeof OperadorSalirRoute
  '/operador/sesion': typeof OperadorSesionRoute
  '/operador/monitoreo': typeof OperatorOperadorMonitoreoRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/operador': typeof OperatorOperadorIndexRoute
  '/demo/banco/rastreos': typeof DemobancoDemoBancoRastreosRoute
  '/operador/cola/$ticketId': typeof OperatorOperadorColaTicketIdRoute
  '/operador/trazas/$traceId': typeof OperatorOperadorTrazasTraceIdRoute
  '/demo/banco': typeof DemobancoDemoBancoIndexRoute
  '/operador/cola': typeof OperatorOperadorColaIndexRoute
  '/operador/trazas': typeof OperatorOperadorTrazasIndexRoute
  '/demo/banco/caso/$ticketId': typeof DemobancoDemoBancoCasoTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_demobanco': typeof DemobancoRouteWithChildren
  '/_operator': typeof OperatorRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/dev/ui': typeof DevUiRoute
  '/operador/clave': typeof OperadorClaveRoute
  '/operador/ingreso': typeof OperadorIngresoRoute
  '/operador/login': typeof OperadorLoginRoute
  '/operador/salir': typeof OperadorSalirRoute
  '/operador/sesion': typeof OperadorSesionRoute
  '/_demobanco/demo/banco': typeof DemobancoDemoBancoRouteWithChildren
  '/_operator/operador/cola': typeof OperatorOperadorColaRouteWithChildren
  '/_operator/operador/monitoreo': typeof OperatorOperadorMonitoreoRoute
  '/_operator/operador/trazas': typeof OperatorOperadorTrazasRouteWithChildren
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/_operator/operador/': typeof OperatorOperadorIndexRoute
  '/_demobanco/demo/banco_/rastreos': typeof DemobancoDemoBancoRastreosRoute
  '/_operator/operador/cola/$ticketId': typeof OperatorOperadorColaTicketIdRoute
  '/_operator/operador/trazas/$traceId': typeof OperatorOperadorTrazasTraceIdRoute
  '/_demobanco/demo/banco/': typeof DemobancoDemoBancoIndexRoute
  '/_operator/operador/cola/': typeof OperatorOperadorColaIndexRoute
  '/_operator/operador/trazas/': typeof OperatorOperadorTrazasIndexRoute
  '/_demobanco/demo/banco/caso/$ticketId': typeof DemobancoDemoBancoCasoTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/dev/ui'
    | '/operador/clave'
    | '/operador/ingreso'
    | '/operador/login'
    | '/operador/salir'
    | '/operador/sesion'
    | '/demo/banco'
    | '/operador/cola'
    | '/operador/monitoreo'
    | '/operador/trazas'
    | '/api/agent/health'
    | '/operador/'
    | '/demo/banco/rastreos'
    | '/operador/cola/$ticketId'
    | '/operador/trazas/$traceId'
    | '/demo/banco/'
    | '/operador/cola/'
    | '/operador/trazas/'
    | '/demo/banco/caso/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/dev/ui'
    | '/operador/clave'
    | '/operador/ingreso'
    | '/operador/login'
    | '/operador/salir'
    | '/operador/sesion'
    | '/operador/monitoreo'
    | '/api/agent/health'
    | '/operador'
    | '/demo/banco/rastreos'
    | '/operador/cola/$ticketId'
    | '/operador/trazas/$traceId'
    | '/demo/banco'
    | '/operador/cola'
    | '/operador/trazas'
    | '/demo/banco/caso/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_demobanco'
    | '/_operator'
    | '/login'
    | '/_authed/chat'
    | '/dev/ui'
    | '/operador/clave'
    | '/operador/ingreso'
    | '/operador/login'
    | '/operador/salir'
    | '/operador/sesion'
    | '/_demobanco/demo/banco'
    | '/_operator/operador/cola'
    | '/_operator/operador/monitoreo'
    | '/_operator/operador/trazas'
    | '/api/agent/health'
    | '/_operator/operador/'
    | '/_demobanco/demo/banco_/rastreos'
    | '/_operator/operador/cola/$ticketId'
    | '/_operator/operador/trazas/$traceId'
    | '/_demobanco/demo/banco/'
    | '/_operator/operador/cola/'
    | '/_operator/operador/trazas/'
    | '/_demobanco/demo/banco/caso/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DemobancoRoute: typeof DemobancoRouteWithChildren
  OperatorRoute: typeof OperatorRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevUiRoute: typeof DevUiRoute
  OperadorClaveRoute: typeof OperadorClaveRoute
  OperadorIngresoRoute: typeof OperadorIngresoRoute
  OperadorLoginRoute: typeof OperadorLoginRoute
  OperadorSalirRoute: typeof OperadorSalirRoute
  OperadorSesionRoute: typeof OperadorSesionRoute
  ApiAgentHealthRoute: typeof ApiAgentHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demobanco': {
      id: '/_demobanco'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemobancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator': {
      id: '/_operator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/clave': {
      id: '/operador/clave'
      path: '/operador/clave'
      fullPath: '/operador/clave'
      preLoaderRoute: typeof OperadorClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/ingreso': {
      id: '/operador/ingreso'
      path: '/operador/ingreso'
      fullPath: '/operador/ingreso'
      preLoaderRoute: typeof OperadorIngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/login': {
      id: '/operador/login'
      path: '/operador/login'
      fullPath: '/operador/login'
      preLoaderRoute: typeof OperadorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/salir': {
      id: '/operador/salir'
      path: '/operador/salir'
      fullPath: '/operador/salir'
      preLoaderRoute: typeof OperadorSalirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/sesion': {
      id: '/operador/sesion'
      path: '/operador/sesion'
      fullPath: '/operador/sesion'
      preLoaderRoute: typeof OperadorSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demobanco/demo/banco': {
      id: '/_demobanco/demo/banco'
      path: '/demo/banco'
      fullPath: '/demo/banco'
      preLoaderRoute: typeof DemobancoDemoBancoRouteImport
      parentRoute: typeof DemobancoRoute
    }
    '/_operator/operador/': {
      id: '/_operator/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperatorOperadorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/operador/cola': {
      id: '/_operator/operador/cola'
      path: '/operador/cola'
      fullPath: '/operador/cola'
      preLoaderRoute: typeof OperatorOperadorColaRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/operador/monitoreo': {
      id: '/_operator/operador/monitoreo'
      path: '/operador/monitoreo'
      fullPath: '/operador/monitoreo'
      preLoaderRoute: typeof OperatorOperadorMonitoreoRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/operador/trazas': {
      id: '/_operator/operador/trazas'
      path: '/operador/trazas'
      fullPath: '/operador/trazas'
      preLoaderRoute: typeof OperatorOperadorTrazasRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/api/agent/health': {
      id: '/api/agent/health'
      path: '/api/agent/health'
      fullPath: '/api/agent/health'
      preLoaderRoute: typeof ApiAgentHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demobanco/demo/banco/': {
      id: '/_demobanco/demo/banco/'
      path: '/'
      fullPath: '/demo/banco/'
      preLoaderRoute: typeof DemobancoDemoBancoIndexRouteImport
      parentRoute: typeof DemobancoDemoBancoRoute
    }
    '/_demobanco/demo/banco_/rastreos': {
      id: '/_demobanco/demo/banco_/rastreos'
      path: '/demo/banco/rastreos'
      fullPath: '/demo/banco/rastreos'
      preLoaderRoute: typeof DemobancoDemoBancoRastreosRouteImport
      parentRoute: typeof DemobancoRoute
    }
    '/_operator/operador/cola/': {
      id: '/_operator/operador/cola/'
      path: '/'
      fullPath: '/operador/cola/'
      preLoaderRoute: typeof OperatorOperadorColaIndexRouteImport
      parentRoute: typeof OperatorOperadorColaRoute
    }
    '/_operator/operador/cola/$ticketId': {
      id: '/_operator/operador/cola/$ticketId'
      path: '/$ticketId'
      fullPath: '/operador/cola/$ticketId'
      preLoaderRoute: typeof OperatorOperadorColaTicketIdRouteImport
      parentRoute: typeof OperatorOperadorColaRoute
    }
    '/_operator/operador/trazas/': {
      id: '/_operator/operador/trazas/'
      path: '/'
      fullPath: '/operador/trazas/'
      preLoaderRoute: typeof OperatorOperadorTrazasIndexRouteImport
      parentRoute: typeof OperatorOperadorTrazasRoute
    }
    '/_operator/operador/trazas/$traceId': {
      id: '/_operator/operador/trazas/$traceId'
      path: '/$traceId'
      fullPath: '/operador/trazas/$traceId'
      preLoaderRoute: typeof OperatorOperadorTrazasTraceIdRouteImport
      parentRoute: typeof OperatorOperadorTrazasRoute
    }
    '/_demobanco/demo/banco/caso/$ticketId': {
      id: '/_demobanco/demo/banco/caso/$ticketId'
      path: '/caso/$ticketId'
      fullPath: '/demo/banco/caso/$ticketId'
      preLoaderRoute: typeof DemobancoDemoBancoCasoTicketIdRouteImport
      parentRoute: typeof DemobancoDemoBancoRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface DemobancoDemoBancoRouteChildren {
  DemobancoDemoBancoIndexRoute: typeof DemobancoDemoBancoIndexRoute
  DemobancoDemoBancoCasoTicketIdRoute: typeof DemobancoDemoBancoCasoTicketIdRoute
}

const DemobancoDemoBancoRouteChildren: DemobancoDemoBancoRouteChildren = {
  DemobancoDemoBancoIndexRoute: DemobancoDemoBancoIndexRoute,
  DemobancoDemoBancoCasoTicketIdRoute: DemobancoDemoBancoCasoTicketIdRoute,
}

const DemobancoDemoBancoRouteWithChildren =
  DemobancoDemoBancoRoute._addFileChildren(DemobancoDemoBancoRouteChildren)

interface DemobancoRouteChildren {
  DemobancoDemoBancoRoute: typeof DemobancoDemoBancoRouteWithChildren
  DemobancoDemoBancoRastreosRoute: typeof DemobancoDemoBancoRastreosRoute
}

const DemobancoRouteChildren: DemobancoRouteChildren = {
  DemobancoDemoBancoRoute: DemobancoDemoBancoRouteWithChildren,
  DemobancoDemoBancoRastreosRoute: DemobancoDemoBancoRastreosRoute,
}

const DemobancoRouteWithChildren = DemobancoRoute._addFileChildren(
  DemobancoRouteChildren,
)

interface OperatorOperadorColaRouteChildren {
  OperatorOperadorColaTicketIdRoute: typeof OperatorOperadorColaTicketIdRoute
  OperatorOperadorColaIndexRoute: typeof OperatorOperadorColaIndexRoute
}

const OperatorOperadorColaRouteChildren: OperatorOperadorColaRouteChildren = {
  OperatorOperadorColaTicketIdRoute: OperatorOperadorColaTicketIdRoute,
  OperatorOperadorColaIndexRoute: OperatorOperadorColaIndexRoute,
}

const OperatorOperadorColaRouteWithChildren =
  OperatorOperadorColaRoute._addFileChildren(OperatorOperadorColaRouteChildren)

interface OperatorOperadorTrazasRouteChildren {
  OperatorOperadorTrazasTraceIdRoute: typeof OperatorOperadorTrazasTraceIdRoute
  OperatorOperadorTrazasIndexRoute: typeof OperatorOperadorTrazasIndexRoute
}

const OperatorOperadorTrazasRouteChildren: OperatorOperadorTrazasRouteChildren =
  {
    OperatorOperadorTrazasTraceIdRoute: OperatorOperadorTrazasTraceIdRoute,
    OperatorOperadorTrazasIndexRoute: OperatorOperadorTrazasIndexRoute,
  }

const OperatorOperadorTrazasRouteWithChildren =
  OperatorOperadorTrazasRoute._addFileChildren(
    OperatorOperadorTrazasRouteChildren,
  )

interface OperatorRouteChildren {
  OperatorOperadorColaRoute: typeof OperatorOperadorColaRouteWithChildren
  OperatorOperadorMonitoreoRoute: typeof OperatorOperadorMonitoreoRoute
  OperatorOperadorTrazasRoute: typeof OperatorOperadorTrazasRouteWithChildren
  OperatorOperadorIndexRoute: typeof OperatorOperadorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorOperadorColaRoute: OperatorOperadorColaRouteWithChildren,
  OperatorOperadorMonitoreoRoute: OperatorOperadorMonitoreoRoute,
  OperatorOperadorTrazasRoute: OperatorOperadorTrazasRouteWithChildren,
  OperatorOperadorIndexRoute: OperatorOperadorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DemobancoRoute: DemobancoRouteWithChildren,
  OperatorRoute: OperatorRouteWithChildren,
  LoginRoute: LoginRoute,
  DevUiRoute: DevUiRoute,
  OperadorClaveRoute: OperadorClaveRoute,
  OperadorIngresoRoute: OperadorIngresoRoute,
  OperadorLoginRoute: OperadorLoginRoute,
  OperadorSalirRoute: OperadorSalirRoute,
  OperadorSesionRoute: OperadorSesionRoute,
  ApiAgentHealthRoute: ApiAgentHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
