"""Problem evidence + operational baseline, computed from the supplied data.

Answers rubric item 1 ("analyze contact reasons, demand patterns, data
quality and operational constraints; establish a baseline") reproducibly:
every number in docs/evidence/baseline_metrics.md is regenerated by

    python -m analysis.baseline_contact_center

against the warehouse built by `python -m data.pipeline --profile all`.
All figures are MEASURED on the historical (synthetic) data — nothing here is
a projection. Projections live in the evaluation report, labeled as such.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb

OUT_JSON = Path("docs/evidence/baseline_metrics.json")
OUT_MD = Path("docs/evidence/baseline_metrics.md")
TEXT_CHANNELS = ("Web Chat", "WhatsApp", "App", "Email", "Web")
GOLD = "gold_contact_demand"


def rows(con, sql):
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def gold_contacts(con) -> dict:
    """The figures that are sums over `gold_contact_demand` (data/gold.py), read from the mart and not from the raw contacts.

    The rest of `compute` needs columns the mart does not carry (segment, hour of day, the survey join, distinct customers) and
    still reads silver. tests/test_baseline_gold.py holds these to the same numbers the contacts table gives."""
    have = {r[0] for r in con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()}
    if GOLD not in have:
        raise SystemExit(f"{GOLD} is not in the warehouse: build it first with `make gold` (python -m data.gold)")
    txn = "reason_category = 'Transaccional'"
    return {
        "contact_reasons": rows(con, f"""SELECT reason_category, sum(n_contacts)::BIGINT AS contacts, round(100.0 * sum(n_contacts) / sum(sum(n_contacts)) OVER (), 1) AS pct
                                         FROM {GOLD} GROUP BY 1 ORDER BY 2 DESC"""),
        "channels": rows(con, f"""SELECT channel, sum(n_contacts)::BIGINT AS contacts, round(100.0 * sum(n_contacts) / sum(sum(n_contacts)) OVER (), 1) AS pct
                                  FROM {GOLD} WHERE {txn} GROUP BY 1 ORDER BY 2 DESC"""),
        # no text-channel contact is 0 %, as in silver; no transactional contact at all stays undefined (NULL)
        "text_channel_pct": con.execute(f"SELECT round(100.0 * coalesce(sum(n_contacts) FILTER (WHERE channel IN {TEXT_CHANNELS}), 0) / sum(n_contacts), 1) FROM {GOLD} WHERE {txn}").fetchone()[0],
        "by_country": rows(con, f"""SELECT country, sum(n_contacts)::BIGINT AS contacts, round(100.0 * sum(n_contacts) / sum(sum(n_contacts)) OVER (), 1) AS pct
                                    FROM {GOLD} WHERE {txn} AND country IS NOT NULL GROUP BY 1 ORDER BY 2 DESC"""),
        "monthly_contacts_median": con.execute(f"""SELECT median(n) FROM (SELECT sum(n_contacts) AS n FROM {GOLD}
            WHERE {txn} AND month >= DATE '2023-07-01' AND month < DATE '2026-06-01' GROUP BY month)""").fetchone()[0],
    }


def compute(con) -> dict:
    g = gold_contacts(con)
    out: dict = {"generated_at": datetime.now(timezone.utc).isoformat(), "source": "warehouse tables (synthetic dataset v1.0.0)"}

    out["contact_reasons"] = g["contact_reasons"]

    out["operations_by_reason"] = rows(con, """
        SELECT reason_category,
               count(*) AS contacts,
               round(avg(duration_seconds), 0) AS aht_s,
               round(quantile_cont(duration_seconds, 0.9), 0) AS aht_p90_s,
               round(avg(wait_time_seconds), 0) AS wait_s,
               round(quantile_cont(wait_time_seconds, 0.9), 0) AS wait_p90_s,
               round(100 * avg(was_resolved::INT), 1) AS fcr_pct,
               round(100 * avg(was_escalated::INT), 1) AS escalated_pct,
               round(100 * avg(requires_followup::INT), 1) AS followup_pct,
               round(100 * avg(CASE WHEN detected_sentiment IN ('Negativo', 'Muy Negativo') THEN 1 ELSE 0 END), 1) AS negative_sentiment_pct
        FROM call_center_interactions GROUP BY 1 ORDER BY 2 DESC""")

    out["satisfaction_by_reason"] = rows(con, """
        SELECT c.reason_category,
               round(avg(s.main_score) FILTER (WHERE s.survey_type = 'CSAT'), 2) AS csat_1_5,
               count(*) FILTER (WHERE s.survey_type = 'CSAT') AS csat_n,
               round(100.0 * (avg(CASE WHEN s.main_score >= 9 THEN 1 ELSE 0 END) FILTER (WHERE s.survey_type = 'NPS')
                            - avg(CASE WHEN s.main_score <= 6 THEN 1 ELSE 0 END) FILTER (WHERE s.survey_type = 'NPS')), 1) AS nps,
               count(*) FILTER (WHERE s.survey_type = 'NPS') AS nps_n
        FROM satisfaction_surveys s JOIN call_center_interactions c USING (interaction_id)
        GROUP BY 1 ORDER BY 1""")

    txn = "reason_category = 'Transaccional'"
    out["transaccional"] = {
        "channels": g["channels"],
        "text_channel_pct": g["text_channel_pct"],
        "by_country": g["by_country"],
        "by_segment": rows(con, f"""SELECT cu.segment, count(*) AS contacts, round(100.0 * count(*) / sum(count(*)) OVER (), 1) AS pct,
                                          round(100 * avg(was_resolved::INT), 1) AS fcr_pct, round(avg(wait_time_seconds), 0) AS wait_s
                                   FROM call_center_interactions c JOIN customers cu USING (customer_id) WHERE {txn} GROUP BY 1 ORDER BY 2 DESC"""),
        "by_day_of_week": rows(con, f"SELECT dayname(interaction_date) AS day, dayofweek(interaction_date) AS dow, count(*) AS contacts FROM call_center_interactions WHERE {txn} GROUP BY 1, 2 ORDER BY 2"),
        "hour_share_min_max_pct": con.execute(f"""SELECT round(100 * min(s), 2), round(100 * max(s), 2) FROM (
            SELECT count(*) / sum(count(*)) OVER () AS s FROM call_center_interactions WHERE {txn} GROUP BY hour(interaction_date))""").fetchone(),
        "monthly_contacts_median": g["monthly_contacts_median"],
        "unique_customers": con.execute(f"SELECT count(DISTINCT customer_id) FROM call_center_interactions WHERE {txn}").fetchone()[0],
    }
    t = next(r for r in out["operations_by_reason"] if r["reason_category"] == "Transaccional")
    out["transaccional"]["agent_hours_per_month_median"] = round(out["transaccional"]["monthly_contacts_median"] * t["aht_s"] / 3600, 0)

    out["text_data_limitations"] = {
        "transcripts": con.execute("SELECT count(*) FROM call_transcripts").fetchone()[0],
        "distinct_customer_texts": con.execute("SELECT count(DISTINCT customer_text) FROM call_transcripts").fetchone()[0],
        "agent_text_unrendered_placeholder_pct": con.execute("SELECT round(100 * avg(CASE WHEN agent_text LIKE '%{%}%' THEN 1 ELSE 0 END), 1) FROM call_transcripts").fetchone()[0],
        "detected_language": rows(con, "SELECT detected_language, count(*) AS n FROM call_transcripts GROUP BY 1"),
        "top_detected_intents": rows(con, "SELECT detected_intents, count(*) AS n FROM call_transcripts GROUP BY 1 ORDER BY 2 DESC LIMIT 3"),
        "contact_reason_equals_category_pct": con.execute("SELECT round(100 * avg(CASE WHEN contact_reason = reason_category THEN 1 ELSE 0 END), 1) FROM call_center_interactions").fetchone()[0],
        # Is transcript text informative about the contact reason at all?
        "balance_request_share_by_reason": rows(con, """
            SELECT c.reason_category, round(100 * avg(CASE WHEN t.customer_text ILIKE '%saldo%' THEN 1 ELSE 0 END), 1) AS pct_mentioning_saldo
            FROM call_transcripts t JOIN call_center_interactions c USING (interaction_id) GROUP BY 1 ORDER BY 1"""),
    }
    out["serving_data_facts"] = {
        "products_by_currency": rows(con, "SELECT currency, count(*) AS n FROM products GROUP BY 1 ORDER BY 2 DESC"),
        "mexico_product_currencies": rows(con, "SELECT p.currency, count(*) AS n FROM products p JOIN customers c USING (customer_id) WHERE c.country = 'México' GROUP BY 1"),
        "credit_products_missing_dpd": con.execute("SELECT count(*) FROM products WHERE product_type IN ('Tarjeta Crédito','Préstamo Personal','Préstamo Hipotecario') AND days_past_due IS NULL").fetchone()[0],
        "credit_products_total": con.execute("SELECT count(*) FROM products WHERE product_type IN ('Tarjeta Crédito','Préstamo Personal','Préstamo Hipotecario')").fetchone()[0],
        "data_as_of": str(con.execute("SELECT max(process_date) FROM transactions").fetchone()[0]),
    }
    return out


def to_markdown(m: dict) -> str:
    def table(rs, cols):
        head = "| " + " | ".join(cols) + " |\n|" + "---|" * len(cols) + "\n"
        return head + "".join("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |\n" for r in rs)

    t = m["transaccional"]
    lim = m["text_data_limitations"]
    s = m["serving_data_facts"]
    return f"""# Baseline metrics (measured, auto-generated)

Generated by `python -m analysis.baseline_contact_center` at {m['generated_at']}.
Every figure below is measured on the supplied (synthetic) historical data. Nothing here is a projection.

## Contact reasons (call_center_interactions)
{table(m['contact_reasons'], ['reason_category', 'contacts', 'pct'])}
## Human-handled baseline by reason
AHT = average handle time. FCR = `was_resolved` (first-contact resolution flag).

{table(m['operations_by_reason'], ['reason_category', 'contacts', 'aht_s', 'aht_p90_s', 'wait_s', 'wait_p90_s', 'fcr_pct', 'escalated_pct', 'followup_pct', 'negative_sentiment_pct'])}
## Satisfaction by reason (satisfaction_surveys joined on interaction_id)
{table(m['satisfaction_by_reason'], ['reason_category', 'csat_1_5', 'csat_n', 'nps', 'nps_n'])}
## Transaccional (account/payment) demand
- Median monthly contacts (Jul 2023 – May 2026): **{t['monthly_contacts_median']:,.0f}**, ≈ **{t['agent_hours_per_month_median']:,.0f} agent-hours/month** of handle time (excluding wait).
- Unique customers who contacted about this: {t['unique_customers']:,}.
- Text channels (chat/WhatsApp/app/email/web) carry **{t['text_channel_pct']}%**; the rest is phone.
- Hour-of-day share ranges {t['hour_share_min_max_pct'][0]}%–{t['hour_share_min_max_pct'][1]}% (flat: no intraday peaks in this synthetic data).

{table(t['channels'], ['channel', 'contacts', 'pct'])}
{table(t['by_country'], ['country', 'contacts', 'pct'])}
{table(t['by_segment'], ['segment', 'contacts', 'pct', 'fcr_pct', 'wait_s'])}
{table(t['by_day_of_week'], ['day', 'contacts'])}
## Limits of the supplied text data
- {lim['transcripts']:,} transcripts contain only **{lim['distinct_customer_texts']} distinct customer texts**; {lim['agent_text_unrendered_placeholder_pct']}% of agent texts contain unrendered template placeholders (e.g. `{{monto}}`).
- `detected_intents` top values: {', '.join(f"{r['detected_intents']} ({r['n']:,})" for r in lim['top_detected_intents'])}.
- `contact_reason` equals `reason_category` in {lim['contact_reason_equals_category_pct']}% of interactions (one field, twice).
- Transcript text does not track the contact reason — share of transcripts mentioning "saldo" by reason: {', '.join(f"{r['reason_category']} {r['pct_mentioning_saldo']}%" for r in lim['balance_request_share_by_reason'])}.
- All transcripts are Spanish ({', '.join(f"{r['detected_language']}={r['n']:,}" for r in lim['detected_language'])}); there is no Portuguese in the dataset.

## Serving-data facts that shape the agent
- Data as of **{s['data_as_of']}** (the agent states this date in every answer).
- Credit products missing `days_past_due`: **{s['credit_products_missing_dpd']:,} of {s['credit_products_total']:,}** — payment-status questions on these escalate (data unavailable) rather than guess.
- Product currencies: {', '.join(f"{r['currency']}={r['n']:,}" for r in s['products_by_currency'])}; Mexican customers' products: {', '.join(f"{r['currency']}={r['n']:,}" for r in s['mexico_product_currencies'])} (no MXN-denominated products at all).
"""


def main() -> None:
    con = duckdb.connect(os.environ.get("DUCKDB_PATH", "data/warehouse/bank.duckdb"), read_only=True)
    m = compute(con)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(m, indent=2, default=str, ensure_ascii=False), encoding="utf-8")
    OUT_MD.write_text(to_markdown(m), encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")  # the report has non-cp1252 characters (Windows consoles)
    print(OUT_MD.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
